# version format
version: 0.1.{build}

environment:
  #GIT_TRACE: 1
  access_token:
    secure: bDZ9LJ84SWlGw/D3R/q3ADwDslfrLNZLMdH3ZRjdi5xwkGanmjf7DvgN+crc4BU/
  psgallery_key:
    secure: FuPgJskczZMptxRgdUlBAy7OYmXBQl4zq86kXXSmBt6wKudnM2PK7W6cM7bj0te1
  coveralls_key:
    secure: bdyanCqxWP0hylNYUvdIl8eUlDMhmIsmeFUNxGwnESlEksBZnxcLhaj1lYVuD7LM
  github_email:
    secure: x5ljenzXfYXkzpEu9eX7AQvb3AkFbiXG2NndMzw9Zc4=
  CODECOV_TOKEN:
    secure: nv7Kt2ldlcFCfK7zX17RrienKXeUQ3AoTZog8m7emylxI3WxUFnJnMV7Ja5gz5/A

skip_tags: true

skip_commits:
  files:
    - docs\*
    - .github\*
    - .vscode\*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md
    - appveyor.yml
    - CHANGELOG.md
  message: /update readme.*|update version.*|update appveyor.*/

only_commits:
  files:
    - build\
    - IdentityCommand\
    - Tests\

image: Visual Studio 2019

install:
  - pwsh.exe -File .\build\install.ps1

build_script:
  - pwsh.exe -File .\build\build.ps1

test_script:
  - pwsh.exe -File .\build\test.ps1

#deploy_script:
  - pwsh.exe -File .\build\deploy-psgallery.ps1
  - pwsh.exe -File .\build\deploy-github.ps1