source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "bulma-clean-theme", "~> 1.0"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

platforms :windows, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.2", platforms: [:windows]
gem "webrick", "~> 1.9"
